#!/usr/bin/env python3
"""Critical volume-coupling line for Regge-weighted QCCG spatial dynamics.

For each preregistered spatial curvature coupling kappa_R, determine kappa_V^c
from the QCCG large-volume move counts alone by requiring

    mean_{N3>=80} [ b(N3)/N3 ] = 0,

where b is the instantaneous volume drift generated by reversible local
Pachner rates

    w = exp[-(kappa_R Delta R + kappa_V Delta N3)/2].

This is the lattice analogue of tuning the volume/cosmological coupling to an
infinite-volume/critical line; it does not use CDT values of mu, lambda or
Gamma as fit targets.

Sources:
- T. Regge, Nuovo Cim. 19 (1961) 558, DOI:10.1007/BF02733251.
- Ambjorn et al., Phys. Rev. D 110, 126006 (2024),
  DOI:10.1103/PhysRevD.110.126006, for the CDT/FRG finite-size critical-path
  comparison and its caveats.
"""
from __future__ import annotations

import argparse
import json
import math
from pathlib import Path

import run_qccg_large_volume_diffusion_scan as base
import run_qccg_curvature_weight_scan as curv


KAPPA_R_VALUES=(-1.0,-0.5,-0.25)
ROOT_TOL=1e-10
R2_SELECTION_TARGET=0.95
LARGE_N_MIN=80

SOURCES=[
    {
        "title":"General relativity without coordinates",
        "author":"T. Regge",
        "doi":"10.1007/BF02733251",
    },
    {
        "title":"Is lattice quantum gravity asymptotically safe? Making contact between causal dynamical triangulations and the functional renormalization group",
        "journal":"Phys. Rev. D 110, 126006 (2024)",
        "doi":"10.1103/PhysRevD.110.126006",
    },
]


def local_moments(counts,kappa_R,kappa_V):
    data=(
        (counts["14"],+3,+curv.DELTA_R_14),
        (counts["41"],-3,-curv.DELTA_R_14),
        (counts["23"],+1,+curv.DELTA_R_23),
        (counts["32"],-1,-curv.DELTA_R_23),
    )
    b=0.0;a=0.0
    for count,dn,dR in data:
        ds=kappa_R*dR+kappa_V*dn
        rate=math.exp(-0.5*ds)
        b += count*rate*dn
        a += count*rate*dn*dn
    return b,a


def sample_rows():
    rows=[]
    for ti,n3 in enumerate(base.TARGETS):
        for s in range(base.SAMPLES_PER_TARGET):
            S,mixed=base.build_target(n3,base.SEED+1000*ti+s)
            rows.append({
                "N3":n3,"sample":s,
                "counts":base.counts(S),
                "mix_pairs_accepted":mixed,
            })
    return rows


def drift_density(rows,kappa_R,kappa_V):
    vals=[]
    for r in rows:
        if r["N3"]<LARGE_N_MIN:
            continue
        b,_a=local_moments(r["counts"],kappa_R,kappa_V)
        vals.append(b/r["N3"])
    return sum(vals)/len(vals)


def solve_kappa_v(rows,kappa_R):
    lo,hi=-4.0,4.0
    flo=drift_density(rows,kappa_R,lo)
    fhi=drift_density(rows,kappa_R,hi)
    if flo*fhi>0:
        raise RuntimeError(f"critical volume-coupling root not bracketed for {kappa_R}: {flo}, {fhi}")
    for _ in range(100):
        mid=0.5*(lo+hi)
        fm=drift_density(rows,kappa_R,mid)
        if abs(fm)<ROOT_TOL:
            return mid,fm
        if fm>0:
            lo=mid
        else:
            hi=mid
    mid=0.5*(lo+hi)
    return mid,drift_density(rows,kappa_R,mid)


def linear_fit(xs,ys):
    xm=sum(xs)/len(xs);ym=sum(ys)/len(ys)
    sxx=sum((x-xm)**2 for x in xs)
    slope=sum((x-xm)*(y-ym) for x,y in zip(xs,ys))/sxx
    intercept=ym-slope*xm
    pred=[intercept+slope*x for x in xs]
    sse=sum((y-p)**2 for y,p in zip(ys,pred))
    sst=sum((y-ym)**2 for y in ys)
    r2=1-sse/sst if sst>1e-18 else 1.0
    return slope,intercept,r2,pred


def fit_potential(rows,kappa_R,kappa_V):
    groups={}
    for r in rows:
        b,a=local_moments(r["counts"],kappa_R,kappa_V)
        groups.setdefault(r["N3"],[]).append((b,a))
    agg=[]
    for N,vals in sorted(groups.items()):
        agg.append({
            "N3":N,
            "drift_rate":sum(x[0] for x in vals)/len(vals),
            "variance_rate":sum(x[1] for x in vals)/len(vals),
        })
    Ns=[float(r["N3"]) for r in agg]
    aa=[r["variance_rate"] for r in agg]
    D0,D1,ar2,_=linear_fit(Ns,aa)
    x=[];up=[]
    for r in agg:
        N=float(r["N3"]);a=r["variance_rate"];b=r["drift_rate"]
        x.append(N**(-2.0/3.0))
        up.append((D0-2*b)/a)
    c,intercept,r2,pred=linear_fit(x,up)
    return {
        "diffusion_D0":D0,"diffusion_D1":D1,"diffusion_linear_r2":ar2,
        "mu":3*c,"lambda":-intercept,"potential_derivative_r2":r2,
        "rows":[{**r,"Uprime_inferred":u,"Uprime_fit":p}
                for r,u,p in zip(agg,up,pred)],
    }


def evidence(eid,obligation,status,note,**metadata):
    return {
        "id":eid,"obligation":obligation,"status":status,
        "engine":"qccg-curvature-critical-line",
        "artifact":"qccg/run_qccg_curvature_critical_line.py",
        "note":note,"metadata":metadata,
    }


def main():
    rows=sample_rows()
    scans=[]
    for kR in KAPPA_R_VALUES:
        kV,res=solve_kappa_v(rows,kR)
        fit=fit_potential(rows,kR,kV)
        scans.append({
            "kappa_R":kR,"kappa_V_critical":kV,
            "large_volume_drift_density_residual":res,
            "potential_fit":fit,
        })

    candidates=[
        x for x in scans
        if x["potential_fit"]["potential_derivative_r2"]>=R2_SELECTION_TARGET
        and x["potential_fit"]["mu"]>0
    ]
    selected=max(candidates,key=lambda x:x["potential_fit"]["potential_derivative_r2"]) if candidates else None
    passed=(selected is not None and all(abs(x["large_volume_drift_density_residual"])<1e-8 for x in scans))

    result={
        "schema":1,
        "scope":"QCCG large-volume zero-drift critical line from local weighted generator; not a continuum fixed point",
        "sources":SOURCES,
        "evidence":[
            evidence(
                "qccg-curvature-volume-critical-line",
                "QCCG_CURVATURE_VOLUME_CRITICAL_LINE",
                "PASS" if passed else "FAIL",
                "For each preregistered negative spatial-curvature coupling, the QCCG large-volume move generator determines a unique volume/cosmological coupling by the zero-drift condition without fitting CDT effective coefficients.",
                kappa_R_values=list(KAPPA_R_VALUES),
                large_N_min=LARGE_N_MIN,
                root_tolerance=ROOT_TOL,
                scans=scans,
                sources=SOURCES,
            ),
            evidence(
                "qccg-curvature-critical-candidate",
                "QCCG_CURVATURE_CRITICAL_CANDIDATE",
                "PASS" if selected is not None else "FAIL",
                "The zero-drift critical-line scan identifies a preregistered curvature-coupling candidate whose instantaneous potential derivative resolves the N3^(-2/3) term with the required fit quality; this candidate is selected before time-evolved confirmation.",
                selection_r2_target=R2_SELECTION_TARGET,
                selected=selected,
                all_candidates=candidates,
                sources=SOURCES,
            ),
            evidence(
                "qccg-curvature-critical-time-confirm-open",
                "QCCG_CURVATURE_CRITICAL_TIME_CONFIRMATION",
                "OPEN",
                "The selected critical-line point must be confirmed with independent-seed state-dependent time evolution before any CDT effective coefficient is promoted.",
                selected=selected,
            ),
        ],
    }

    p=Path(args.out);p.parent.mkdir(parents=True,exist_ok=True)
    p.write_text(json.dumps(result,indent=2,sort_keys=True)+"\n",encoding="utf-8")
    if any(e["status"]=="FAIL" for e in result["evidence"][:2]):
        raise SystemExit("QCCG curvature critical-line audit failed")


if __name__=="__main__":
    ap=argparse.ArgumentParser();ap.add_argument("--out",required=True);args=ap.parse_args();main()
